---
layout: post
title: Jenkins Workflow Plugin
author: Cedric
cover: jenkins-banner
tags: [Jenkins,Docker]
---

# Workflow

[source,groovy]
-----
docker.image("codetroopers/jenkins-slave-jdk8-restx")
    .inside('-v /var/jenkins_home/.m2:/home/jenkins/.m2'){ // # <1>
    git branch: 'master', url: 'https://github.com/code-troopers/jenkins-workflow-demo-repo.git' // # <2>
    sh "MAVEN_OPTS=-Dfile.encoding=UTF-8 mvn clean install -B -Ppackage" // # <3>
    step([$class: 'ArtifactArchiver', artifacts: 'srv/target/dependency/webapp-runner.jar, srv/target/*.war, run.sh') // # <4>
    step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml']) // # <5>
}
-----
<1> Run in container with shared m2 local repository
<2> Clone the repo
<3> Classic run install
<4> Archive artefacts
<5> Archive test results


## Group commands in stage

[source,groovy]
-----
stage 'build' // # <1>
    docker.image("codetroopers/jenkins-slave-jdk8-restx").inside('-v /var/jenkins_home/.m2:/home/jenkins/.m2'){
        git branch: 'master', url: 'https://github.com/code-troopers/jenkins-workflow-demo-repo.git'
        sh "MAVEN_OPTS=-Dfile.encoding=UTF-8 mvn clean install -B -Ppackage"
        step([$class: 'ArtifactArchiver', artifacts: 'srv/target/dependency/webapp-runner.jar, srv/target/*.war, run.sh')
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
    }
-----
<1> Name step to allow grouping execution

## Stash files for a later stage

[source,groovy]
-----
stage 'build'
    docker.image("codetroopers/jenkins-slave-jdk8-restx").inside('-v /var/jenkins_home/.m2:/home/jenkins/.m2'){
        git branch: 'master', url: 'https://github.com/code-troopers/jenkins-workflow-demo-repo.git'
        sh "MAVEN_OPTS=-Dfile.encoding=UTF-8 mvn clean install -B -Ppackage"
        step([$class: 'ArtifactArchiver', artifacts: 'srv/target/dependency/webapp-runner.jar, srv/target/*.war, run.sh')
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
        stash includes: 'run.sh,srv/target/dependency/webapp-runner.jar,srv/target/*.war,Dockerfile', name: 'dockerBuild' // # <1>
    }
-----
<1> Stash the files to reuse in a later stage

## Stage to build a docker image


[source,groovy]
-----
stage 'dockerbuild' // # <1>
node{ // # <2>
  ws{ // # <3>
    unstash 'dockerBuild' // # <4>
    docker.build("codetroopers/jenkins-workflow-demo:${env.BUILD_ID}") // # <5>
  }
}
-----
<1> Create a new stage
<2> Node is a build runner
<3> Requires a new workspace
<4> Unstash previously stashed files under name 'dockerBuild'
<5> Build a docker image with the current $BUILD_ID

## Multibranch

* put build script in SCM
* make branches build automatically (without history mix)

=> Jenkinsfile

[source,groovy]
-----
stage 'build'
    docker.image("codetroopers/jenkins-slave-jdk8-restx").inside('-v /var/jenkins_home/.m2:/home/jenkins/.m2'){
        checkout scm // # <1>
        sh "MAVEN_OPTS=-Dfile.encoding=UTF-8 mvn clean install -B -Ppackage"
        step([$class: 'ArtifactArchiver', artifacts: 'srv/target/dependency/webapp-runner.jar, srv/target/*.war, run.sh')
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
        stash includes: 'run.sh,srv/target/dependency/webapp-runner.jar,srv/target/*.war,Dockerfile', name: 'dockerBuild'
    }

stage 'dockerbuild'
node{
  ws{
    unstash 'dockerBuild'
    docker.build("codetroopers/jenkins-workflow-demo:${env.BUILD_ID}")
  }
}
-----
<1> Replace `git clone` with `checkout scm` to ensure we are on the proper repo/branch

## Wait for user interaction

[source,groovy]
-----
stage 'build'
    docker.image("codetroopers/jenkins-slave-jdk8-restx").inside('-v /var/jenkins_home/.m2:/home/jenkins/.m2'){
        git branch: 'master', url: 'https://github.com/code-troopers/jenkins-workflow-demo-repo.git'
        sh "MAVEN_OPTS=-Dfile.encoding=UTF-8 mvn clean install -B -Ppackage"
        step([$class: 'ArtifactArchiver', artifacts: 'srv/target/dependency/webapp-runner.jar, srv/target/*.war, run.sh')
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
        stash includes: 'run.sh,srv/target/dependency/webapp-runner.jar,srv/target/*.war,Dockerfile', name: 'dockerBuild'
    }

stage 'dockerbuild'
node{
    ws{
        unstash 'dockerBuild'
        def built = docker.build("codetroopers/jenkins-workflow-demo:${env.BUILD_ID}")
        input 'Is everything ok ? Run app ?' // # <1>
        echo "We can run the docker-compose up here"
        def outcome = input message: 'We can even have parameters to answer this question', parameters: [ // # <2>
            [name: 'myChoice', description: 'My choice', choices: 'Choice 1\nChoice 2\nChoice 3', $class: 'ChoiceParameterDefinition']
        ]
        echo "You have chosen ${outcome}" // # <3>
    }
}
-----
<1> Input pauses the build and allows to go on or abort the build
<2> It can also ask for input with parameters (pauses and allows reusing the value)
<3> Answer from previous input is reused in printed message
