export default {
  autoprefixer: true, // http://cssnano.co/optimisations/autoprefixer/
  calc: true, // http://cssnano.co/optimisations/calc/
  colormin: true, // http://cssnano.co/optimisations/colormin/
  convertValues: true, // http://cssnano.co/optimisations/convertValues/
  core: true, // http://cssnano.co/optimisations/core/
  discardComments: true, // http://cssnano.co/optimisations/discardComments/
  discardDuplicates: true, // http://cssnano.co/optimisations/discardDuplicates/
  discardEmpty: true, // http://cssnano.co/optimisations/discardEmpty/
  discardOverridden: true, // http://cssnano.co/optimisations/discardOverridden/
  discardUnused: true, // http://cssnano.co/optimisations/discardUnused/
  filterOptimiser: true, // http://cssnano.co/optimisations/filterOptimiser/
  filterPlugins: true, // http://cssnano.co/optimisations/filterPlugins/
  functionOptimiser: true, // http://cssnano.co/optimisations/functionOptimiser/
  mergeIdents: true, // http://cssnano.co/optimisations/mergeIdents/
  mergeLonghand: true, // http://cssnano.co/optimisations/mergeLonghand/
  mergeRules: true, // http://cssnano.co/optimisations/mergeRules/
  minifyFontValues: true, // http://cssnano.co/optimisations/minifyFontValues/
  minifyGradients: true, // http://cssnano.co/optimisations/minifyGradients/
  minifyParams: true, // http://cssnano.co/optimisations/minifyParams/
  minifySelectors: true, // http://cssnano.co/optimisations/minifySelectors/
  normalizeCharset: true, // http://cssnano.co/optimisations/normalizeCharset/
  normalizeString: true, // http://cssnano.co/optimisations/normalizeString/
  normalizeUnicode: true, // http://cssnano.co/optimisations/normalizeUnicode/
  normalizeUrl: true, // http://cssnano.co/optimisations/normalizeUrl/
  orderedValues: true, // http://cssnano.co/optimisations/orderedValues/
  reduceBackgroundRepeat: true, // http://cssnano.co/optimisations/reduceBackgroundRepeat/
  reduceDisplayValues: true, // http://cssnano.co/optimisations/reduceDisplayValues/
  reduceIdents: true, // http://cssnano.co/optimisations/reduceIdents/
  reduceInitial: true, // http://cssnano.co/optimisations/reduceInitial/
  reducePositions: true,  // http://cssnano.co/optimisations/reducePositions/
  reduceTimingFunctions: true, // http://cssnano.co/optimisations/reduceTimingFunctions/
  reduceTransforms: true, // http://cssnano.co/optimisations/reduceTransforms/
  styleCache: true, // http://cssnano.co/optimisations/styleCache/
  svgo: true, // http://cssnano.co/optimisations/svgo/
  uniqueSelectors: true, // http://cssnano.co/optimisations/uniqueSelectors/
  zindex: true // http://cssnano.co/optimisations/zindex/
};
