local_backend: true

backend:
  # For use in development, will actually be set automatically
  # name: proxy
  # proxy_url: http://localhost:8081/api/v1
  # branch: main
  # --
  # For use in production on GitHub
  name: github
  repo: code-troopers/code-troopers.github.io
  branch: main
  # --
  # For use in production on netlify
  # name: git-gateway
  # branch: main



media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    media_folder: ".."
    path: "{{slug}}" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Aliases", name: "aliases", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false}
      - {label: "Image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Work" # Used in the UI, ie.: "New Post"
    folder: "site/content/work" # The path to the folder where the documents are stored
    media_folder: ".."
    path: "{{slug}}" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false}
      - {label: "Image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "home"
    label: "Home"
    files:
      - file: "site/content/_index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: text}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Text, name: text, widget: string}
          - {label: Liens, name: liens, widget: list, fields: [{label: Text, name: text, widget: string}, {label: Url, name: url, widget: string}]}
      - file: "site/data/menu.json"
        label: Menu
        name: menu
        fields:
          - {label: Links, name: links, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Id, name: id, widget: string}, {label: Url, name: url, widget: string}]}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
