name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hugo-webpack
    - name: Build app
      run: docker run --rm -v ${PWD}/site:/usr/src/app/site -v ${PWD}/src:/usr/src/app/src -v ${PWD}/dist:/usr/src/app/dist hugo-webpack npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
            dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:    
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          fetch-depth: 0
          
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    
      - name: clean
        run: |
          git rm -r -q *
          git reset HEAD CNAME
          git checkout -- CNAME
          git commit -m "Clean older version"
          
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          
      - name: Update site and push
        run: |
          git add -A
          git commit -a -m "New release"
          git push -u origin gh-pages
