name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - uses: reitzig/actions-asciidoctor@v2.0.1
      with:
        version: 2.0.18

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
